In [2]:
import pandas as pd             # data package
import matplotlib.pyplot as plt # graphics 
import datetime as dt
import numpy as np

import requests, io             # internet and input tools  
import zipfile as zf            # zip file tools 
import os  

#import weightedcalcs as wc
#import numpy as np

import pyarrow as pa
import pyarrow.parquet as pq

In [3]:
date = "2024-12"

my_key = "&key=34e40301bda77077e24c859c6c6c0b721ad73fc7"
# This is my key. I'm nice and I have it posted. If you will be doing more with this
# please get your own key!

In [11]:
end_use = "hs?get=CTY_NAME,CON_VAL_MO,CAL_DUT_MO,I_COMMODITY,I_COMMODITY_SDESC,I_COMMODITY_LDESC"

surl = "https://api.census.gov/data/timeseries/intltrade/imports/" + end_use 

surl  = surl + my_key + "&time=" + "from+2013-01" + "&COMM_LVL=HS10" 

url = surl
    
r = requests.get(url) 
    
print(r)
    
foo = pd.DataFrame(r.json()[1:]) # This then converts it to a dataframe
    # Note that the first entry is the labels

foo.columns = r.json()[0]

<Response [200]>

In [12]:
foo.head()

,CTY_NAME,CON_VAL_MO,CAL_DUT_MO,I_COMMODITY,I_COMMODITY_SDESC,I_COMMODITY_LDESC,time,COMM_LVL
0,TOTAL FOR ALL COUNTRIES,773010,0,0602400000,"ROSES, GRAFTED OR NOT","ROSES, GRAFTED OR NOT",2013-01,HS10
1,TOTAL FOR ALL COUNTRIES,6177543,0,0602902000,"ORCHID PLANTS, LIVE","ORCHID PLANTS, LIVE",2013-01,HS10
2,TOTAL FOR ALL COUNTRIES,135786,0,0602903010,CHRYSANTHEMUMS WITH SOIL ATTACHED TO ROOTS,CHRYSANTHEMUMS WITH SOIL ATTACHED TO ROOTS,2013-01,HS10
3,TOTAL FOR ALL COUNTRIES,169439,0,0602903090,"HERBACEOUS PERENNIALS,WTH SOIL ATTACHED,LIVE,N...",HERBACEOUS PERENNIALS WITH SOIL ATTACHED TO RO...,2013-01,HS10
4,TOTAL FOR ALL COUNTRIES,2177498,25345,0602904000,HERBACEOUS PERENNIALS WTHOUT SOIL ATTACHED NESOI,"HERBACEOUS PERENNIALS, LIVE, WITHOUT SOIL ATTA...",2013-01,HS10

In [13]:
# Extract unique commodity codes with their descriptions
unique_commodities = foo[['I_COMMODITY', 'I_COMMODITY_SDESC', 'I_COMMODITY_LDESC']].drop_duplicates(subset='I_COMMODITY')

# Display the result
unique_commodities.head()

,I_COMMODITY,I_COMMODITY_SDESC,I_COMMODITY_LDESC
0,0602400000,"ROSES, GRAFTED OR NOT","ROSES, GRAFTED OR NOT"
1,0602902000,"ORCHID PLANTS, LIVE","ORCHID PLANTS, LIVE"
2,0602903010,CHRYSANTHEMUMS WITH SOIL ATTACHED TO ROOTS,CHRYSANTHEMUMS WITH SOIL ATTACHED TO ROOTS
3,0602903090,"HERBACEOUS PERENNIALS,WTH SOIL ATTACHED,LIVE,N...",HERBACEOUS PERENNIALS WITH SOIL ATTACHED TO RO...
4,0602904000,HERBACEOUS PERENNIALS WTHOUT SOIL ATTACHED NESOI,"HERBACEOUS PERENNIALS, LIVE, WITHOUT SOIL ATTA..."

In [14]:
unique_commodities.shape

(22634, 3)

In [15]:
unique_commodities.to_csv('.\\data\\unique_commodities.csv', index=False)